### ISSUE TITLE
How can I login username and password

### ISSUE THREAD

**Issue by farihulrouf** [stonaxstudios/OurVLE#1]
Hi. How can I login for username and password ?

**Comment by macsual** [comment]
Hello, in this repository, the read me states:

> ... It is not meant to be used with a standard Moodle installation and is primarily meant for use by students of The University of The West Indies, Mona campus in Jamaica.

With that being said, you would have to attend the University of The West Indies in Jamaica and be a currently registered student, in which case the username would be your UWI student ID number and your password would be your date of birth in the _YYYYMMDD_ format by default if/until you change it to something else.

**Comment by farihulrouf** [comment]
May I change the String URL "http://ourvle.mona.uwi.edu" in the _MoodleConstants_ class to "https://demo.moodle.net/"?

**Comment by macsual** [comment]
I would suppose you could, although I would just like to let you know that this app has never been tested against another Moodle instance. Any issues that could arise may come from differences in the https://demo.moodle.net/ site configuration. I'd actually be interested in knowing how that goes.
